target 'FakererNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'SwiftOverlays', '~> 3.0.0'
pod 'SwiftyJSON'
pod "Hero"
pod 'SwifterSwift'
# Pods for FakerNews

end

