# FriendlyChat Codelab

use_frameworks!
platform :ios, '9.0'

pod 'Firebase/Storage'
pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod ‘GTMSessionFetcher’
pod 'Firebase/Auth'
  pod "SwiftSpinner"
target 'testFirebaseStringPusher4' do
end
